language: python

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py35

# command to install dependencies
install: pip install tox
# command to run tests
script: tox -e $TOX_ENV
# codecov
before_install:
  - pip install codecov
after_success:
  - codecov
